import type { Metadata } from "next";
import { PageIntro } from "@/components/site/page-intro";
import { ChatInterface } from "@/components/chat/chat-interface";

export const metadata: Metadata = {
  title: "Ask the Assistant",
  description:
    "Chat with the Always In The Club Foundation AI assistant — ask about programs, the book, how to volunteer, or how to support our mission.",
  alternates: { canonical: "/chat" },
  // Hidden from search engines — the assistant is a utility surface,
  // not landing-page content we want indexed.
  robots: { index: false, follow: false },
};

export default function ChatPage() {
  return (
    <main>
      <PageIntro
        eyebrow="AI Assistant"
        title="Ask us anything."
        subtitle="Programs, the book, how to give, how to get involved."
      />

      <section className="bg-warm-white pb-20 pt-4 sm:pb-28">
        <div className="mx-auto max-w-3xl px-5 sm:px-8">
          <div className="flex h-[min(80svh,720px)] flex-col overflow-hidden rounded-2xl border border-border bg-cream shadow-soft-sm">
            <ChatInterface variant="page" />
          </div>
          <p className="mt-4 text-center text-[12px] leading-relaxed text-warm-gray">
            Responses are generated by AI. For anything sensitive — large or
            unusual gifts, partnership inquiries, legal or tax questions —
            please email{" "}
            <a
              href="mailto:Info@AlwaysInTheClub.org"
              className="font-semibold text-red no-underline transition-colors hover:text-red-deep"
            >
              Info@AlwaysInTheClub.org
            </a>
            .
          </p>
        </div>
      </section>
    </main>
  );
}
